### ISSUE TITLE
cshape tool requires markdown

### ISSUE THREAD

**Issue by nandub** [cortesi/countershape#5]
The README says that python-markdown2 is optional, however if I use `cshape` it throws an error.

```
$ cshape doc-src /tmp/cshape-test
Traceback (most recent call last):
  File "/usr/local/bin/cshape", line 80, in <module>
    main()
  File "/usr/local/bin/cshape", line 76, in main
    c.main()
  File "/usr/local/bin/cshape", line 52, in main
    d = doc.Doc(args[0], options.options)
  File "/Library/Python/2.7/site-packages/countershape/doc.py", line 328, in __init__
    model.BaseApplication.__init__(self, d)
  File "/Library/Python/2.7/site-packages/countershape/model.py", line 376, in __init__
    self.addPage(i)
  File "/Library/Python/2.7/site-packages/countershape/model.py", line 489, in addPage
    page._prime(self)
  File "/Library/Python/2.7/site-packages/countershape/doc.py", line 246, in _prime
    self.load()
  File "/Library/Python/2.7/site-packages/countershape/doc.py", line 256, in load
    execfile(_ConfFile, glob, loc)
  File "index.py", line 17, in <module>
AttributeError: 'module' object has no attribute 'Markdown'
```

**Comment by nandub** [comment]
Never received a response. Closing for now.
